### ISSUE TITLE
About pretrained model of dense cl

### ISSUE THREAD

**Issue by zxk19981227** [CoinCheung/denseCL#7]
i tried to download the pretrained model of dense cl but the link seems unavailable. Could you update the link?

**Comment by CoinCheung** [comment]
Hi, 

Which link? Make sure you can download from github pages.

**Comment by zxk19981227** [comment]
https://github.com/CoinCheung/denseCL/releases/download/v0.0.1/r50_checkpoint_0199.pth.tar

**Comment by CoinCheung** [comment]
Does it work now?

**Comment by zxk19981227** [comment]
Yes it works. Thank you for your reply.
